name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install pnpm
      uses: pnpm/action-setup@v3

    - name: Set node version to ${{ matrix.node_version }}
      uses: actions/setup-node@v4
      with:
         node-version: ${{ matrix.node_version }}  
         
    - name: Install deps
      run: pnpm install
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1      
    
    - name: Install dependencies
      run: pnpm install
    - name: Build
      run: pnpm run docs:build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/.vitepress/dist
        publish_branch: gh-pages
