name: Deploy VitePress site to Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: gh-pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4  #          升级到v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.6.3

      - name: Setup Node.js
        uses: actions/setup-node@v4  #         升级到v4
        with:
          node-version: '22'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install 

      - name: Build with VitePress
        run: |
          pnpm run docs:build
          touch docs/.vitepress/dist/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3  # 保持v3或使用最新兼容版本
        with:
          path: docs/.vitepress/dist

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4  # 使用官方部署Action